version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app/"
    command: bash -c 'echo 'sleep' && sleep 4 && echo 'starting' && npm start'

  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data: