version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"
    command: bash -c 'echo "sleep" && sleep 4 && echo "starting" && npm start'

  caddy:
    image: caddy:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./public:/etc/caddy/public"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
