version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app/"
    command: bash -c 'echo 'sleep' && sleep 4 && echo 'starting' && npm start'

